/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Quiz.gui;

import Quiz.DAO.UserDAO;
import Quiz.dbutil.DBConnection;
import Quiz.pojo.UserProfile;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author gouru
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }

    /**,
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        quit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        admin = new javax.swing.JRadioButton();
        student = new javax.swing.JRadioButton();
        pwd = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 204, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/WpsqQq3.gif"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 320, 420, 340);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel2.setText("PASSWORD");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(620, 560, 140, 24);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel3.setText("USER NAME");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(620, 500, 140, 24);

        name.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(name);
        name.setBounds(810, 500, 150, 30);

        login.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        login.setText("LOGIN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login);
        login.setBounds(680, 630, 85, 31);

        quit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        quit.setText("QUIT");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });
        jPanel1.add(quit);
        quit.setBounds(810, 630, 75, 31);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("USER TYPE");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(620, 690, 90, 22);

        buttonGroup1.add(admin);
        admin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        admin.setText("ADMIN");
        jPanel1.add(admin);
        admin.setBounds(620, 750, 85, 31);

        buttonGroup1.add(student);
        student.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        student.setText("STUDENT");
        jPanel1.add(student);
        student.setBounds(810, 750, 107, 31);

        pwd.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        pwd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(pwd);
        pwd.setBounds(810, 560, 150, 26);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pexels-tirachard-kumtanom-733852 (1).jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 1080, 810);

        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(650, 340, 41, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1065, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        if(name.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "PLEASE ENTER USER NAME","ERROR!",JOptionPane.ERROR_MESSAGE);
        }
        else if(pwd.getPassword().length==0)
        {
            JOptionPane.showMessageDialog(null, "PLEASE ENTER PASSWORD","ERROR!",JOptionPane.ERROR_MESSAGE);
        }
        else if(admin.isSelected()==false&&student.isSelected()==false)
        {
            JOptionPane.showMessageDialog(null, "PLEASE SELECT USERTYPE ","ERROR!",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            try{
                String usertype;
                String pass=String.valueOf(pwd.getPassword());
                if(admin.isSelected()==true)
                {
                    usertype="ADMIN"; 
                   
                }
                else
                    usertype="STUDENT";
                boolean x=UserDAO.Login(name.getText(),pass,usertype);
                if(x)
                {
                    JOptionPane.showMessageDialog(null, "LOGGED IN SUCCESSFULLY","SUCCESS",JOptionPane.INFORMATION_MESSAGE);
                   UserProfile.setUsername(name.getText());
                     if(admin.isSelected()==true)
                    {
                        usertype="ADMIN"; 
                        AdminOptionFrame aop=new AdminOptionFrame();
                        aop.setVisible(true);
                        this.dispose();
                    }
                     else{
                        usertype="STUDENT";
                        StudentOptionsFrame sop=new StudentOptionsFrame();
                        sop.setVisible(true);
                        this.dispose();
                     }
                }
                else
                    JOptionPane.showMessageDialog(null, "INVALID USERNAME PASSWORD OR YOU MAY NOT BE "+usertype+"","ERROR!",JOptionPane.ERROR_MESSAGE);
            
            
            }
            catch(Exception ex)
            {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_loginActionPerformed

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
       this.dispose();
       DBConnection.closeConnection();
    }//GEN-LAST:event_quitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton admin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField pwd;
    private javax.swing.JButton quit;
    private javax.swing.JRadioButton student;
    // End of variables declaration//GEN-END:variables

    
}
